file(GLOB _root_documents "${PROJECT_ROOT}/*.md")
file(GLOB_RECURSE _docs_documents "${PROJECT_ROOT}/docs/*.md")
set(_documents ${_root_documents} ${_docs_documents})
set(_failures "")
foreach(_document IN LISTS _documents)
  file(READ "${_document}" _content)
  string(REGEX MATCHALL "\\[[^]]*\\]\\([^)]+\\)" _links "${_content}")
  get_filename_component(_directory "${_document}" DIRECTORY)
  foreach(_link IN LISTS _links)
    string(REGEX REPLACE "^[^(]*\\(([^)]+)\\)$" "\\1" _target "${_link}")
    if(_target MATCHES "^(https?://|mailto:|#)")
      continue()
    endif()
    string(REGEX REPLACE "#.*$" "" _target "${_target}")
    if(_target STREQUAL "")
      continue()
    endif()
    get_filename_component(_resolved "${_directory}/${_target}" ABSOLUTE)
    if(NOT EXISTS "${_resolved}")
      list(APPEND _failures "${_document}: ${_target}")
    endif()
  endforeach()
endforeach()

if(_failures)
  list(JOIN _failures "\n  " _failure_text)
  message(FATAL_ERROR "Broken repository-relative Markdown links:\n  ${_failure_text}")
endif()
message(STATUS "Checked repository-relative links in ${_documents}")
