function(usdphysics_assert_target_dependencies)
  cmake_parse_arguments(ARG "" "TARGET" "ALLOWED_PUBLIC;ALLOWED_PRIVATE" ${ARGN})
  if(NOT ARG_TARGET OR NOT TARGET ${ARG_TARGET})
    message(FATAL_ERROR "usdphysics_assert_target_dependencies requires an existing TARGET")
  endif()

  foreach(_kind IN ITEMS PUBLIC PRIVATE)
    if(_kind STREQUAL "PUBLIC")
      set(_property INTERFACE_LINK_LIBRARIES)
      set(_allowed ${ARG_ALLOWED_PUBLIC})
    else()
      set(_property LINK_LIBRARIES)
      set(_allowed ${ARG_ALLOWED_PRIVATE})
    endif()
    get_target_property(_links ${ARG_TARGET} ${_property})
    if(NOT _links)
      set(_links "")
    endif()
    foreach(_link IN LISTS _links)
      if(NOT _link IN_LIST _allowed)
        message(FATAL_ERROR
          "${ARG_TARGET} has forbidden ${_kind} dependency '${_link}'; "
          "allowed: ${_allowed}")
      endif()
    endforeach()
  endforeach()
endfunction()
